### user register
POST http://localhost:4000/users-api/users 
Content-Type: application/json 

{
    "firstname":"ishu",
    "lastname":"chirra",
    "email":"ishu.author@example.com",
    "password":"author",
    "profileImageUrl":"http://exmaple.com/avatars/author.png"
}     

###  user login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{ 
    "email":"ishu.author@example.com",
    "password":"author"
    
}

### author register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{ 
    "firstname":"ishu",
    "lastname":"chirra",
    "email":"ravi@123",
    "password":"ravi",
    "profileImageUrl":"http://exmaple.com/avatars/author.png"
}     


###author login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"ravi@123",
    "password":"ravi"
}

   
### create article
post http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author": "69aeed1e43931c8a23d6c54e",
    "title": "Sample Article",
    "category": "Tech",
    "content": "This is a sample article content."
}

### get all users (debug)
GET http://localhost:4000/common-api/users


###read articles
GET http://localhost:4000/author-api/articles/698c8c23d217c96b416e00d9


### update article
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"69aeed1e43931c8a23d6c54e",
    "articleId":"69aeeeb543931c8a23d6c560",
    "title":"test1",
    "category":"gaming",
    "content":"content ot test1 article"

}


### delete the article
PATCH http://localhost:4000/author-api/articles/69aeed1e43931c8a23d6c54e/status
Content-Type: application/json

{
  "isArticleActive": false
}


###logout
GET http://localhost:4000/common-api/logout


###block user
PUT http://localhost:4000/admin-api/users/698c8c23d217c96b416e00d9/block

###unblock user
PUT http://localhost:4000/admin-api/users/698c8c23d217c96b416e00d9/unblock


###change passwords
PUT http://localhost:4000/common-api/change-passwords
Content-Type: application/json

{
    "userId":"698c8c23d217c96b416e00d9",
    "currentPassword":"author",
    "newPassword":"newpassword"
}

###comments to the article
PUT http://localhost:4000/user-api/articles/69aeeeb543931c8a23d6c560/comments
Content-Type: application/json

{
  "user":"698c8c23d217c96b416e00d9",
  "comment":"good"
}

###for restoring the login
GET http://localhost:4000/common-api/check-auth


###test
GET http://localhost:4000/test

###
GET http://localhost:4000/hello